NinoS99/MSCI342Project

index.html
knowledgeBase.html
login.html

Updated homepage to include Knowledge Base button, created Knowledge Base html file. Structure of CSS/HTML code can be improved and HTML eventually will need to be merged with PHP.

HTML update

---

src/surveyPage.php

Formatting looks much cleaner.
I like the name change from Credit Card Survey to User Survey.

Changed some HTML Formatting

---

index.html
knowledgeBase.html
login.html
src/submit.php
src/surveyPage.php

Had to change from sql to query for consistency and formatted to suit other files

Formatting and Consistency Variable Changes

---

index.html
knowledgeBase.html
login.html
src/submit.php
src/surveyPage.php

* submit page
* HTML update
Updated homepage to include Knowledge Base button, created Knowledge Base html file
* Adding comments to code
* Changed some HTML Formatting
* formatting and new website output (#3)
Looks good
Co-authored-by: Nino S <spasiknino23@gmail.com>
Co-authored-by: dylanh107 <dylanh107@gmail.com>
Co-authored-by: j7mah <72579412+j7mah@users.noreply.github.com>
Co-authored-by: OmnipotentJon <jc2black@uwaterloo.ca>
Co-authored-by: NinoS99 <67913300+NinoS99@users.noreply.github.com>

Formatting and Consistency Variable Changes (#4)

---

creditCardCompanies.html
howCreditCardsworks.html
knowledgeBase.html
typesOfCreditCards.html

Knowledge based HTML files to learn about basic credit card information

Add HTML files for credit card knowledge pages

---

src/surveyPage.php

Please let Nino review,
These are changes for Nino to build on for his queries,
NOTE: there are blocks of code that are commented out for future use (eg. hidden values)
THX

Insert into user_responses along with javascript changes (NINO REVIEW)

---

howCreditCardsworks.html
index.html

Implemented bootstrap and made some changes to the design of the homepage. Will continue to improve elements (such as button text font). Will also try to tweak the other pages so that they resemble this template in next pull.

Updated Homepage UI

---

creditCardApplications.php
creditCardCompanies.php
creditCardFees.php
howCreditCardsworks.php
knowledgeBase.php
typesOfCreditCards.php

modified title boxes in the KnowledgeBase, please ensure that there are no mistakes

Changed titleboxes in KnowledgeBase to jumbotron titles (bootstrap)

---

src/matchingMethod.php

just some last minute fixed to the matching method, wrong variable name was used in a couple of lines

fixing errors in matching method

---

creditCardApplications.php
creditCardFees.php
creditCardRewardPrograms.php
howCreditCardsworks.php
knowledgeBase.php

Updated the following files:
- creditCardApplications.php 
- creditCardFees.php 
- howCreditCardsworks.php 
- creditCardRewardPrograms.php 
- knowledgeBase.php

Updated knowledge base section with a new rewards page and minor interface changes

---

src/DBController.php
src/allCards.php
src/submit.php

Files to check/test:
- allCards.php (in src folder): new page to output all the credit cards companies, names and networks
- DBController.php (in src folder): new page to help get query of matched credit card
- submit.php (in src folder): new page to get to allCards.php page and also home to export button
User stories Completed:
1) As a user I want to export my selection results to keep track of my selections  
Tasks Completed: 
- Created button to export information on matched credit card
- Created SQL query to grab information of the matched credit card
- Created PHP function to combine button and query
2) As a user I want to see all the credit cards to see which all the options available 
Tasks Completed: 
- Created hyperlink to a page that displays all the credit cards in the …

Export and display list of all credit card features

---

src/matchingMethod.php

Quick PR for Jon
Made changes so that a website for a credit card that is recommended for user is hyperlinked. 
Gave it a quick test and it worked. 
Thanks

directing user to credit card website

---

src/matchingMethod.php
src/submit.php

- Added for loop to account for multiple credit card outputs

Minor Excel Fix

---

src/matchingMethod.php

quick bug fixes
- matching method didn't populate credit card array properly, that has been fixed

quick fixes to matching method

---

creditCardApplications.php
creditCardCompanies.php
creditCardFees.php
creditCardRewardPrograms.php
creditScores.php
howCreditCardsworks.php
knowledgeBase.php
typesOfCreditCards.php

Updated the following files:
creditCardApplications.php (one minor change to layout title)
creditCardCompanies.php (one minor change to layout title)
creditCardFees.php (one minor change to layout title)
howCreditCardsworks.php (one minor change to layout title)
creditCardRewardPrograms.php (one minor change to layout title)
typesOfCreditCards.php (one minor change to layout title)
knowledgeBase.php (included a button to access credit scores page)
creditScores.php (new page!, please check/test)
This request refers the following user stories:
1) As a user I want to learn more about credit scores so I can improve my credit card knowledge.
Tasks Completed:
Added in an additional page with details on the credit scores
Created a button to new page and return button on new page back to …

Updated knowledge base feature with new page on credit scores and quick formatting fixes

---

knowledgeBase.php
src/allCards.php

Updated the following files:
src/allCards.php
This request refers the following user story: "As a user I want to filter credit cards by credit card network (Visa, Mastercard, AE etc.) so I can customize my view of cards for a selected network."
Tasks Completed:
Added in filter options on credit card companies in the display all cards page (our group decided to look at companies rather than networks as specified on our sprint plan since it would allow for more filter opportunities)
Test cases:
Make sure you can filter by Visa, Mastercard, and American Express. If it works you should see a new view with the applied filter and corresponding cards. (Tested this on my own local server and it works so far)
Make sure you can use the return button on the webpage to redirect back to submit.php …

Filter feature for all cards page

---

src/surveyPage.php

Updated the following files:
src/surveyPage.php
This request refers the following user story: "As a user I want to email my survey results to myself to keep for reference."
Tasks Completed:
Create email template (subject, message, email address that send the email)
Test cases:
Check email has been sent to the user's specified email address when the user clicks on the submit button in the survey.php page. I tested this on my own local server and it works so far, email information is written on every line specified in the code (good visibility) and it was sent to my junk inbox.

Email feature

---

creditCardApplications.php
creditCardCompanies.php
creditCardFees.php
creditCardRewardPrograms.php
howCreditCardsworks.php
typesOfCreditCards.php

Revised UI for the 6 Knowledge Base pages. Added padding to buttons and text elements within pages, changed text types for headings and paragraphs on each page. Overall the Knowledge Base should be much easier to read for users. Also added embedded links for credit card company pictures on the credit card companies page.
User story addressed: As a user I want to navigate the various offerings of CreditSimple with ease
Unit Tests (please check these before merging):
1. Ensure that all 6 buttons for each Knowledge Base page still work
2. Ensure that when you click on the credit card company pictures of the company page, it will lead you to that company's website

Knowledge Base UI Overhaul

---

src/surveyPage.php

- Added negative check to survey annual fee, messages under error.
- Formatted survey page and made inquiries set into a table to justify and make everything look nice

Formatting survey page and Data validation

---

src/matchingMethod.php
src/submit.php

Unit Testing:
Tested each case for fluid table outputting
Tested each case for excel outputting
Changes:
Made the table consistent
Made the css colour changes to be consistent with the rest of the website

Formatting Changes to Submit Page

---

src/allCards.php

Made changes on the following page: allCards.php
- Centered the table that outputs the credit cards
- Added a column of the link to the website for each credit card 
- Changed it so the user can filter by credit card company
Thanks

changes to the All Cards page
